---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/stream2loggly
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - save_cache:
          key: v1-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/shync/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  node-8:
    <<: *test
    docker:
      - image: node:8

workflows:
  version: 2
  "stream2loggly":
    jobs:
      - node-latest
      - node-8
